source "https://rubygems.org"

ruby "2.6.0"

gem "jekyll"
gem "rouge"
gem "jekyll-zopfli"
gem "jekyll-brotli"
gem "jekyll-paginate"
gem "jekyll-assets"
gem "jekyll-sitemap"
gem "webp-ffi"
gem "sass"
gem "sprockets-es6"
gem "liquid-md5"
gem "uglifier"
gem "therubyracer"
