source "https://rubygems.org"

ruby "2.7.2"

gem "jekyll"
gem "rouge"
gem "kramdown"
gem "kramdown-parser-gfm"
gem "jekyll-zopfli"
gem "jekyll-brotli"
gem "jekyll-paginate"
gem "jekyll-assets"
gem "sprockets", "~> 3.3"
gem "jekyll-sitemap"
gem "webp-ffi"
gem "sass"
gem "sprockets-es6"
gem "liquid-md5"
gem "uglifier"
gem "therubyracer"
gem "jekyll-web_monetization"