name = "philna-sh"
main = "./dist/_worker.js/index.js"
pages_build_output_dir = "./dist"

# Set this to today's date
compatibility_date = "2026-03-04"
compatibility_flags = [ "nodejs_compat" ]

[assets]
directory = "./dist"
not_found_handling = "404-page"

[observability]
enabled = true