#!/bin/bash -i
GIT_REPO=$HOME/repos/philnash.git
TMP_GIT_CLONE=$HOME/tmp/git/philnash
PUBLIC_WWW=/var/www/html

git clone $GIT_REPO $TMP_GIT_CLONE
cd $TMP_GIT_CLONE
bundle install
JEKYLL_ENV=production bundle exec jekyll build --source $TMP_GIT_CLONE --destination $PUBLIC_WWW
cd $GIT_REPO
rm -Rf $TMP_GIT_CLONE
exit
