name: "Trigger deployment"

on:
  workflow_dispatch:
  schedule:
    - cron: "5 0 * * *"

jobs:
  run-updater:
    runs-on: ubuntu-latest
    steps:
      - name: Hit Cloudflare webhook with curl
        run: |
          curl -X POST "${{ secrets.CLOUDFLARE_WEBHOOK }}"
